name: Repo Template Setup

on:
  push:
    branches:
      - main  # Change to your default branch if not "main"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run repo-template-setup.py
        run: python repo-template-setup.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "Automated changes by Repo Template Setup Action" || (echo "No changes to commit. Something went wrong" && exit 1)
          git push